name: CI & Automated Testing

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-macOS:
    name: Build & Test (macOS / Xcode)
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ['15.4', 'latest-stable']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Build Package
        run: swift build -v

      - name: Run Tests
        run: swift test --parallel -v
